In [5]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_excel("C:/Users/Games 10/Downloads/relatorio-de-faltantes.xls")
alunos = df["Aluno(a)"]
telefones = df["Telefone(s)"]
numA = len(alunos)
numT = len(telefones)
c = 0
while c < numA and c < numT:
  print(alunos[c])
  print(telefones[c])
  c+=1

ALEXIS PEREIRA DA MATA
1194581-8816
ALLAN SANDES DOS SANTOS
112317-3272
ANDREZA DOS REIS PORTO
1198013-4504
ANNI CAROLINE CARVALHO TORRES
112384-5118
ANNI CAROLINE CARVALHO TORRES
1198280-5312
ARIADNE MARIANO DE OLIVEIRA
1195492-5619
CAROLINE MARCOLINO DA SILVA
1196818-3581
CLAUDIO DANIEL TORRES DE OLIVEIRA PATEZ
1198598-1850
EMERSON COSTA ARAUJO
1197469-2906
EMILLY MOREIRA DA SILVA
11946361147
EMILY EDUARDA ARAGÃO DE OLIVEIRA
1198489-2443
EMMILY JULIANA SILVA KUMAGAI
11958812980
FERNANDA LAZZERI FERNANDES
1195236-8027
FERNANDA NOBREGA ROSA
112613-3979
GABRIEL GUILHERME DUQUE DA SILVA
1196512-9662
GABRIEL SANTOS DE ARAUJO
11954809558
GABRIEL SANTOS SOARES
112774-7848
GEORGE SOUZA DE BRITO
1196275-7530
GEOVANA HUNGRIA ROCHA
1194485-4304
GEOVANNA LOPES DE SOUSA
1196122-1727
GUSTAVO SANTOS ORTEGA
1198422-1578
HENRICO WILLIAM MATTOSO
1195300-5994
HENRIQUE NOVAES DE JESUS
1195717-4549
ISAAC GABRIEL DA SILVA COSTA
1196764-6673
ISABELA PEREIRA DA SILVA
1195449-4303
ISABELA RODRIGUES DE MORAES ARAUJO
1195727-1090
ISAQUE QUEIROZ DOS SANTOS
113542-0451
JAQUELINE SOLEDAD CONTRERAS TIOSI
115231-0262
JEAN CARLOS SANTANA SILVA
114461-0552
JOAO VICTOR BARROS DA SILVA
1196442-6595
JOÃO VITOR GONÇALVES DA SILVA
1194890-9678
JOELMA QUEIROZ DA SILVA SANTOS
1196024-1589
JORGE LUIZ MARTINS DE JESUS CARNEIRO
113052-3075
JOSE DJACI SILVEIRA SILVA
1195460-5394
JULIA ANTUNES FUSTE
1198183-6628
JULIA CAMPOS VEIGA
1194700-162
JULIO CESAR DA COSTA
112352-3783
KAIK OLIVEIRA BARROS
1198268-8034
KAUÃ CAVALCANTE DOS REIS
1194134-6814
KEILANE BISPO SANTOS
1198255-2007
LARA RITHIELLI ARAUJO ROCHA
1195654-9445
LARISSA DE OLIVEIRA ALVES
1193237-2790
LEANDRA GOMES BORGES
1199407-9001
LILIAN ILARI SILVA SANTOS
1198564-9434
LUCAS GROSS
11981192090
LUIGI SENA
1198420-7878
LUIZ HENRIQUE RODRIGUES DA SILVA
112069-7214
MAGDARLINE PHANORD
1195377-4356
MARCELLY SOARES DE SOUZA
1194905-7534
MARIA CECILIA PEREIRA SILVA
1194446-1332
MARIA DO SOCORRO MAIA DIAS
1195148-5519
MARIANA SOFIA SIMÕES SANTOS
1198367-8953
MATHEUS YURI DE JESUS SILVA
1195958-3291
MELISSA TORRES TEIXERA
1196808-5982
MICAELLA FERREIRA DA SILVA
1196131-3567
MURILO HENRIQUE DE JESUS SILVA
1195958-3291
NICOLE MENDES DE SOUZA
1194657-7735
NICOLY CAVALCANTE DE SOUSA
1195198-6007
PABLO HENRIQUE OLIVEIRA COSTA
119) 5998-0383
RAISSA OLIVEIRA DE SA
112940-5725
RAMON DUARTE RIBEIRO
115058-4173
RAYANY GABRIELLY SANTOS FERREIRA
1194003-5187
RICARDO AUGUSTO OLIVEIRA SILVA
1194831-7761
ROBERTA CHIARA TORQUEMADA BARRETO
112947-3294
RUBEN CORREIA SILVA
1196346-5640
RYAN GABRIEL DA CONCEIÇÃO SILVA
112083-3375
RYAN SOARES LAZARO
1199399-5486
SAMIRA HUNGRIA ROCHA
1194485-4304
SAMUEL COLPAERT DOS SANTOS
1195788-7270
SAMUEL DOS SANTOS SOUSA
1198823-0513
SAMUEL DOS SANTOS SOUSA
1198823-0513
SAMYRA EMANUELLE PAIVA
1191007-2382
SOPHIA ALVES DE LIMA
112063-2203
THALITA TURQUESA QUILLE FLORES
1198452-5560
TIAGO COSTA DE SANTANA
1196576-9199
UESILE NATÃ SILVA SANTOS
1198564-9434
VICENTE FRANÇA DE JESUS
112890-9898
VILMAR DE SOUSA FERREIRA
1197689-5487
VITORIA JESUS SILVA OLIVEIRA
1195853-8995
WEDJA WANESSA DA SILVA SANTOS
1196869-2640

,Matrícula,Aluno(a),Telefone(s),Faltas,Última falta,Situação,Turma,Disciplina,Professor,Último contato
0,18846,ALEXIS PEREIRA DA MATA,1194581-8816,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17257,ALLAN SANDES DOS SANTOS,112317-3272,NaN,02/10/2021,Ativa,FS14/003 (09/11/2019),You Rock 02/03,MATHEUS ZANOTTO ALVES DE SOUZA PADALINO,NaN
2,17377,ANDREZA DOS REIS PORTO,1198013-4504,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18425,ANNI CAROLINE CARVALHO TORRES,112384-5118,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18525,ANNI CAROLINE CARVALHO TORRES,1198280-5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
75,18524,UESILE NATÃ SILVA SANTOS,1198564-9434,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,18946,VICENTE FRANÇA DE JESUS,112890-9898,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,16938,VILMAR DE SOUSA FERREIRA,1197689-5487,4.0,02/10/2021,Ativa Quitada,FS08/006 (11/09/2021),Trabalho de Conclusão de Curso,LEANDRO SANTOS AZEVEDO,30/09/2021 11:17-Falei com: VALDI HORTENCIO Gr...
78,18629,VITORIA JESUS SILVA OLIVEIRA,1195853-8995,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,18473,WEDJA WANESSA DA SILVA SANTOS,1196869-2640,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import pandas as pd
import time
import pyautogui
from selenium import webdriver
from selenium.webdriver.common.keys import Keys


df = pd.read_excel("C:/Users/User/Desktop/arroz.xlsx")
alunos = df["Aluno(a)"]
telefones = df["Telefone(s)"]
numA = len(alunos)
numT = len(telefones)
i = 0

browser = webdriver.Chrome()
browser.get('https://messages.google.com/web/conversations?pli=1')
time.sleep(6)


while i < numA and i < numT:
    time.sleep(20)
    browser.find_element_by_xpath('/html/body/mw-app/mw-bootstrap/div/main/mw-main-container/div/mw-main-nav/div/mw-fab-link/a').click()
    time.sleep(5)
    pyautogui.click(x=536, y=238)
    pyautogui.write('{}'.format(telefone[i]))
    time.sleep(2)
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x=568, y=650)
    time.sleep(5)
    pyautogui.write("OLA BOA TARDE SOMOS DA ESCOLA START PRO IPIRANGA ESTAMOS ENTRANDO EM CONTATO PARA SABER O MOTIVO DAS FALTAS DO ALUNO(A) {0}  POR FAVOR ENTRAR EM CONTATO COM ESSE TELEFONE 11 996614346 PARA JUSTIFICAR AS FALTAS".format(alunos[(i)]))
    time.sleep(5)
    pyautogui.press('enter')
    time.sleep(5)
    i+= 1

In [ ]:
import time
import pyautoguiOLA BOA TARDE SOMOS DA ESCOLA START PRO IPIRANGA ESTAMOS ENTRANDO EM CONTATO PARA SABER O MOTIVO DAS FALTAS DO ALUNO(A) ANNI CAROLINE CARVALHO TORRES  POR FAVOR ENTRAR EM CONTATO COM ESSE TELEFONE 11 996614346 PARA JUSTIFICAR AS FALTAS


time.sleep(2)
pyautogui.position()

c = int(0)
while c < 90:
 print(c++)

In [32]:
c = int(0) 
while c < 90: 
    print(c)
    c= int(c + 1)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89